"""
AI Service for Bill Summarization
Uses extractive summarization for quick, accurate summaries
"""
import re
from datetime import datetime
import os
import chromadb
from chromadb.utils import embedding_functions
try:
    from textblob import TextBlob
except ImportError:
    pass # Handled gracefully

import traceback
try:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel
    TRANSFORMERS_AVAILABLE = True
except ImportError:
    TRANSFORMERS_AVAILABLE = False

# Local Model State
_LOCAL_MODEL = None
_LOCAL_TOKENIZER = None
_LOCAL_MODEL_LOADED = False
_LOCAL_MODEL_LOADING = False

def lazy_load_model():
    """Lazy load the local LoRA model to avoid blocking startup."""
    global _LOCAL_MODEL, _LOCAL_TOKENIZER, _LOCAL_MODEL_LOADED, _LOCAL_MODEL_LOADING
    
    if _LOCAL_MODEL_LOADED or _LOCAL_MODEL_LOADING or not TRANSFORMERS_AVAILABLE:
        return _LOCAL_MODEL_LOADED
        
    try:
        _LOCAL_MODEL_LOADING = True
        print("\n[AI Service] Loading local LoRA model into memory (this may take a minute)...")
        
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        lora_dir = os.path.join(project_root, "notebooks", "lora_model")
        
        if not os.path.exists(lora_dir):
            print(f"[AI Service] LoRA adapter not found at {lora_dir}. Using extractive fallback.")
            _LOCAL_MODEL_LOADING = False
            return False
            
        base_model_name = "unsloth/Llama-3.2-3B-Instruct-bnb-4bit"
        
        # Load tokenizer
        _LOCAL_TOKENIZER = AutoTokenizer.from_pretrained(base_model_name)
        
        # Determine device
        device_map = "auto" if torch.cuda.is_available() else "cpu"
        print(f"[AI Service] Using device map: {device_map}")
        
        # Load base model
        base_model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            device_map=device_map,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            low_cpu_mem_usage=True
        )
        
        # Load LoRA adapter
        _LOCAL_MODEL = PeftModel.from_pretrained(base_model, lora_dir)
        
        print("[AI Service] Successfully loaded local LoRA model!\n")
        _LOCAL_MODEL_LOADED = True
        
    except Exception as e:
        print(f"[AI Service] Failed to load local model: {e}")
        traceback.print_exc()
    finally:
        _LOCAL_MODEL_LOADING = False
        
    return _LOCAL_MODEL_LOADED

def generate_lora_summary(text):
    """Generate a summary using the local fine-tuned LoRA model."""
    if not lazy_load_model() or not _LOCAL_MODEL or not _LOCAL_TOKENIZER:
        return None
        
    try:
        print("[AI Service] Generating summary using local LoRA model...")
        # Prompt structure based on Llama-3-Instruct format
        messages = [
            {"role": "system", "content": "You are an expert legal translator. Summarize this Indian legislative text into plain, accessible English suitable for a high school reading level. Retain all factual penalties, dates, and jurisdictions. Format the output clearly."},
            {"role": "user", "content": f"Simplify this legal text:\n\n{text[:6000]}"}
        ]
        
        prompt = _LOCAL_TOKENIZER.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        
        inputs = _LOCAL_TOKENIZER(prompt, return_tensors="pt")
        if torch.cuda.is_available():
            inputs = {k: v.to("cuda") for k, v in inputs.items()}
            
        # Generate
        with torch.no_grad():
            outputs = _LOCAL_MODEL.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.3,
                top_p=0.9,
                do_sample=True,
                pad_token_id=_LOCAL_TOKENIZER.eos_token_id
            )
            
        # Decode only the newly generated tokens
        input_length = inputs["input_ids"].shape[1]
        generated_tokens = outputs[0][input_length:]
        result = _LOCAL_TOKENIZER.decode(generated_tokens, skip_special_tokens=True)
        
        return result.strip()
    except Exception as e:
        print(f"[AI Service] Local model generation failed: {e}")
        return None

# Guardrails
LEGAL_DISCLAIMER = "\n\n---\n**Disclaimer:** This summary was generated by an AI model for educational purposes only. It does not constitute legal advice. Please refer to the official legislative text for accurate legal interpretations."

def check_input_guardrails(query):
    """Input guardrails: ensure query is relevant to legal search."""
    non_legal_keywords = ["write a story", "joke", "recipe", "code", "poem", "how to make", "ignore previous"]
    query_lower = query.lower()
    for kw in non_legal_keywords:
        if kw in query_lower:
            return False, "Query rejected: The semantic distance indicates this query is non-legal. Please ask questions related to Indian legislation."
    return True, ""

def append_legal_disclaimer(summary):
    """Output guardrail: Append legal disclaimer"""
    return summary + LEGAL_DISCLAIMER

def analyze_sentiment(text):
    """Analyze sentiment of the bill text. Returns score between -1.0 and 1.0"""
    if not text:
        return 0.0
    try:
        blob = TextBlob(text[:5000]) # Analyze first 5000 chars for speed
        return blob.sentiment.polarity
    except Exception:
        return 0.0

def semantic_search(query, n_results=5):
    """Query ChromaDB for semantic search."""
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    db_path = os.path.join(project_root, "backend", "instance", "chroma_db")
    
    if not os.path.exists(db_path):
        print(f"ChromaDB not found at {db_path}")
        return []
        
    try:
        client = chromadb.PersistentClient(path=db_path)
        sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
        collection = client.get_collection(name="legal_bills", embedding_function=sentence_transformer_ef)
        
        results = collection.query(
            query_texts=[query],
            n_results=n_results
        )
        
        formatted_results = []
        if results and results['metadatas'] and len(results['metadatas'][0]) > 0:
            for i in range(len(results['documents'][0])):
                formatted_results.append({
                    "text": results['documents'][0][i],
                    "metadata": results['metadatas'][0][i],
                    "distance": results['distances'][0][i] if 'distances' in results and results['distances'] else None
                })
        return formatted_results
    except Exception as e:
        print(f"Error in semantic search: {e}")
        return []


def generate_bill_summary(bill_data, content_data):
    """
    Generate AI summary for a bill
    Uses extractive summarization to create concise summaries
    
    Args:
        bill_data: Bill metadata (title, ministry, status, etc.)
        content_data: Bill content (sections, paragraphs, full_text)
    
    Returns:
        dict with summary and metadata
    """
    
    # Extract key information
    title = bill_data.get('title', 'Untitled Bill')
    ministry = bill_data.get('ministry', '').strip()
    status = bill_data.get('status', '').strip()
    introduction_date = bill_data.get('introduction_date')
    
    # Get content
    full_text = content_data.get('full_text', '')
    sections = content_data.get('sections', [])
    paragraphs = content_data.get('paragraphs', [])
    
    # Build summary
    summary_parts = []
    
    # 1. Title and Basic Info
    summary_parts.append(f"## {title}\n")
    
    # Only add ministry and status if they have values
    if ministry:
        summary_parts.append(f"\n**Ministry:** {ministry}")
    if status:
        summary_parts.append(f"\n**Status:** {status}")
    
    if introduction_date:
        try:
            date_obj = datetime.fromisoformat(introduction_date.replace('Z', '+00:00'))
            formatted_date = date_obj.strftime('%B %d, %Y')
            summary_parts.append(f"\n**Introduced:** {formatted_date}")
        except:
            pass
    
    # 2. Extract bill overview from sections
    overview = extract_bill_overview(sections)
    if overview:
        summary_parts.append(f"\n\n### Overview\n{overview}")
    
    # 3. Extract key objectives from content
    objectives = extract_objectives(full_text, sections)
    if objectives:
        summary_parts.append(f"\n\n### Key Objectives\n{objectives}")
    
    # 4. Extract main provisions
    provisions = extract_provisions(sections)
    if provisions:
        summary_parts.append(f"\n\n### Main Provisions\n{provisions}")
    
    # 5. Extract penalties/enforcement if available
    penalties = extract_penalties(sections, paragraphs)
    if penalties:
        summary_parts.append(f"\n\n### Penalties & Enforcement\n{penalties}")
    
    # 6. Add scope and impact
    scope = extract_scope(full_text, sections)
    if scope:
        summary_parts.append(f"\n\n### Scope\n{scope}")
    
    # Try Local LoRA Model First!
    lora_summary_text = generate_lora_summary(full_text)
    
    if lora_summary_text:
        summary_text = f"## {title}\n"
        if ministry: summary_text += f"\n**Ministry:** {ministry}"
        if status: summary_text += f"\n**Status:** {status}"
        
        if introduction_date:
            try:
                date_obj = datetime.fromisoformat(introduction_date.replace('Z', '+00:00'))
                formatted_date = date_obj.strftime('%B %d, %Y')
                summary_text += f"\n**Introduced:** {formatted_date}"
            except:
                pass
                
        summary_text += f"\n\n### AI Generative Summary\n{lora_summary_text}\n\n*(Generated by fine tuned lora model)*"
        summary_type = 'generative_lora'
    else:
        # Fallback to extractive approach
        summary_text = ''.join(summary_parts)
        if len(summary_text) < 200:
            summary_text = generate_simple_summary_from_sections(title, sections, paragraphs)
        summary_type = 'extractive'
        
    # Append legal disclaimer (Guardrails)
    summary_text = append_legal_disclaimer(summary_text)
    
    # Analyze Sentiment
    sentiment_score = analyze_sentiment(full_text)
    
    return {
        'summary': summary_text,
        'summary_type': summary_type,
        'generated_at': datetime.utcnow().isoformat(),
        'word_count': len(summary_text.split()),
        'confidence': 0.95 if summary_type == 'generative_lora' else 0.85,
        'sentiment_score': sentiment_score
    }


def extract_objectives(full_text, sections):
    """Extract key objectives from bill content"""
    objectives = []
    
    # Look for objective-related keywords
    objective_keywords = [
        'objective', 'purpose', 'aim', 'intent', 'seeks to', 
        'is enacted', 'provides for', 'establishes', 'bill seeks'
    ]
    
    # Search in sections
    for section in sections[:10]:  # First 10 sections
        section_title = section.get('section', '').lower()
        section_content = section.get('content', '')
        
        # Check if section content mentions the bill's purpose
        if any(keyword in section_content.lower() for keyword in objective_keywords):
            # Extract relevant sentences
            sentences = extract_sentences(section_content, max_sentences=2)
            for sentence in sentences:
                if len(sentence) > 30 and any(keyword in sentence.lower() for keyword in objective_keywords):
                    objectives.append(f"• {sentence}")
    
    return '\n'.join(objectives[:5]) if objectives else None


def extract_bill_overview(sections):
    """Extract the main overview/introduction of the bill"""
    overview = []
    
    # Usually the first few sections contain the overview
    for section in sections[:5]:
        content = section.get('content', '').strip()
        section_name = section.get('section', '').strip().lower()
        
        # Look for introduction or overview sections
        if not section_name or 'introduc' in section_name.lower() or len(content) > 100:
            # Get meaningful content (skip dates and short texts)
            if len(content) > 50 and not re.match(r'^(Introduced|Passed|Pending)', content):
                sentences = extract_sentences(content, max_sentences=3)
                if sentences:
                    overview.extend(sentences)
                    break
    
    if overview:
        return ' '.join(overview[:3])  # Max 3 sentences
    return None


def generate_simple_summary_from_sections(title, sections, paragraphs):
    """Generate a simple summary when detailed extraction fails"""
    summary_parts = [f"## {title}\n"]
    
    # Get the first substantial section content
    for section in sections:
        content = section.get('content', '').strip()
        if len(content) > 100 and not re.match(r'^(Introduced|Passed|Pending)', content):
            summary_parts.append(f"\n{content}")
            break
    
    # If still not enough, use paragraphs
    if len(''.join(summary_parts)) < 200 and paragraphs:
        summary_parts.append(f"\n\n### Key Points\n")
        for para in paragraphs[:3]:
            if len(para) > 50:
                summary_parts.append(f"• {para}\n")
    
    return ''.join(summary_parts)


def extract_penalties(sections, paragraphs):
    """Extract penalty and enforcement information"""
    penalties = []
    
    # Look for penalty-related sections
    penalty_keywords = ['penalty', 'penalties', 'offence', 'punishment', 'fine', 'imprisonment']
    
    for section in sections:
        section_name = section.get('section', '').lower()
        content = section.get('content', '')
        
        if any(keyword in section_name for keyword in penalty_keywords):
            sentences = extract_sentences(content, max_sentences=3)
            for sentence in sentences:
                if len(sentence) > 20:
                    penalties.append(f"• {sentence}")
    
    # Also check paragraphs
    if not penalties:
        for para in paragraphs:
            if any(keyword in para.lower() for keyword in penalty_keywords):
                if len(para) > 50:
                    penalties.append(f"• {para}")
                    if len(penalties) >= 2:
                        break
    
    return '\n'.join(penalties[:3]) if penalties else None


def extract_provisions(sections):
    """Extract main provisions from sections"""
    provisions = []
    
    # Look for provision-related sections
    provision_keywords = [
        'provision', 'regulation', 'prohibition', 'promotion',
        'authority', 'power', 'requirement', 'establishment'
    ]
    
    for section in sections:
        section_name = section.get('section', '').strip()
        content = section.get('content', '')
        
        # If section has a meaningful name, use it
        if section_name and len(section_name) > 5:
            # Check if it's a provision section
            if any(keyword in section_name.lower() for keyword in provision_keywords):
                # Extract first sentence or two
                sentences = extract_sentences(content, max_sentences=2)
                if sentences:
                    provision_text = ' '.join(sentences)
                    provisions.append(f"**{section_name}:** {provision_text}")
    
    return '\n\n'.join(provisions[:5]) if provisions else None


def extract_scope(full_text, sections):
    """Extract scope and applicability"""
    scope_text = []
    
    # Look for scope-related keywords
    scope_keywords = [
        'applies to', 'applicable', 'scope', 'extends to',
        'shall apply', 'jurisdiction', 'territory'
    ]
    
    # Search in full text
    if full_text:
        for keyword in scope_keywords:
            pattern = rf'[^.]*{keyword}[^.]*\.'
            matches = re.findall(pattern, full_text, re.IGNORECASE)
            for match in matches[:2]:
                cleaned = match.strip()
                if 20 < len(cleaned) < 200:
                    scope_text.append(f"• {cleaned}")
    
    return '\n'.join(scope_text[:3]) if scope_text else None


def extract_sentences(text, max_sentences=3):
    """Extract sentences from text"""
    if not text:
        return []
    
    # Split by period, but be careful with abbreviations
    sentences = re.split(r'\.(?!\d)(?![A-Z]{1,3}\.)', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    # Clean up
    clean_sentences = []
    for sentence in sentences[:max_sentences]:
        # Remove extra whitespace
        sentence = ' '.join(sentence.split())
        # Remove leading numbers/bullets
        sentence = re.sub(r'^[\d\.\-\•\*\(\)]+\s*', '', sentence)
        if sentence:
            clean_sentences.append(sentence)
    
    return clean_sentences


def generate_quick_summary(bill_data):
    """
    Generate a quick one-line summary when full content is not available
    """
    title = bill_data.get('title', 'Bill')
    ministry = bill_data.get('ministry', '')
    status = bill_data.get('status', '')
    
    summary = f"This bill titled '{title}' "
    
    if ministry:
        summary += f"from the {ministry} "
    
    if status:
        summary += f"is currently {status.lower()}. "
    else:
        summary += "is under consideration. "
    
    summary += "Detailed provisions and objectives are being analyzed."
    
    return {
        'summary': summary,
        'summary_type': 'quick',
        'generated_at': datetime.utcnow().isoformat(),
        'word_count': len(summary.split()),
        'confidence': 0.5
    }
