"""
VidhanAI summarization service.

Phase 1 of the semester plan (reproducibility): this module is intentionally
honest about which model produced each summary. There are three backends:

    1. `groq_expert` (default, production): Groq `groq/compound` (formerly
       `llama-3.3-70b-versatile`, retired) with the domain-specific expert
       prompt. This is what currently serves every user-facing summary.
    2. `local_lora` (Phase 2 only): the QLoRA-fine-tuned Llama-3.2-3B adapter
       at ``notebooks/lora_model``. Opt-in via the ``VIDHANAI_USE_LORA=1`` env
       var so we never silently fall back from a real adapter run to Groq.
    3. `extractive` (last-resort fallback): rule-based extraction from the
       bill text when neither model is available. Only used when both LLM
       backends fail or no full text is present.

Every summary records ``model_version`` so we can audit which backend produced
it and ``guardrail_applied`` so reviewers can confirm disclaimer enforcement.
"""
from __future__ import annotations

import logging
import os
import re
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Optional imports - handled gracefully so the module loads even if a heavy
# dependency (transformers, peft, chromadb, textblob, groq) is missing.
# ---------------------------------------------------------------------------
try:
    import chromadb
    from chromadb.utils import embedding_functions
    CHROMADB_AVAILABLE = True
except ImportError:  # pragma: no cover
    CHROMADB_AVAILABLE = False

try:
    from textblob import TextBlob
    TEXTBLOB_AVAILABLE = True
except ImportError:  # pragma: no cover
    TEXTBLOB_AVAILABLE = False

try:
    from groq import Groq
    GROQ_AVAILABLE = True
except ImportError:  # pragma: no cover
    GROQ_AVAILABLE = False

# Lazy-loaded heavy imports (TensorFlow, transformers, peft)
# Only imported when USE_LOCAL_LORA=1 and model is actually needed
TRANSFORMERS_AVAILABLE = None
_torch = None
_AutoModelForCausalLM = None
_AutoTokenizer = None
_PeftModel = None

def _lazy_load_transformers():
    """Lazy-load transformers, torch, and peft only when needed."""
    global TRANSFORMERS_AVAILABLE, _torch, _AutoModelForCausalLM, _AutoTokenizer, _PeftModel
    if TRANSFORMERS_AVAILABLE is not None:
        return TRANSFORMERS_AVAILABLE
    try:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer
        from peft import PeftModel
        _torch = torch
        _AutoModelForCausalLM = AutoModelForCausalLM
        _AutoTokenizer = AutoTokenizer
        _PeftModel = PeftModel
        TRANSFORMERS_AVAILABLE = True
    except ImportError:
        TRANSFORMERS_AVAILABLE = False
    return TRANSFORMERS_AVAILABLE


# ---------------------------------------------------------------------------
# Configuration / constants
# ---------------------------------------------------------------------------

EXPERT_SYSTEM_PROMPT = (
    "You are an expert legal translator. Summarize this Indian legislative "
    "text into plain, accessible English suitable for a high school reading "
    "level. Retain all factual penalties, dates, and jurisdictions. Format "
    "the output clearly with headings and bullet points. Do not include "
    "meta-commentary about your approach, notes to the reader, or headings "
    "such as 'Here is the summary' / 'How I approached this'."
    "\n\nIMPORTANT: Start your response with a '## TL;DR' section containing "
    "exactly 3 concise bullet points that capture the most critical takeaways "
    "(purpose, key change/penalty, impact). This TL;DR must be the very first "
    "content after any header we prepend."
)

TLDR_EXTRACT_PROMPT = (
    "Extract exactly 3 concise bullet points from the following legislative "
    "summary that capture: (1) the bill's core purpose, (2) the most significant "
    "penalty/change/provision, (3) the practical impact or next step. "
    "Return ONLY the 3 bullets, one per line, starting with '• '."
)

LEGAL_DISCLAIMER = (
    "\n\n---\n**Disclaimer:** This summary was generated by an AI model for "
    "educational purposes only. It does not constitute legal advice. Please "
    "refer to the official legislative text for accurate legal interpretations."
)

# NOTE: the paper referenced `llama-3.3-70b-versatile`, which Groq has since
# retired. `groq/compound` is the current flagship text model on this key.
GROQ_MODEL_NAME = os.environ.get("VIDHANAI_GROQ_MODEL", "groq/compound")
LORA_BASE_MODEL = os.environ.get("VIDHANAI_LORA_BASE", "unsloth/Llama-3.2-3B-Instruct-bnb-4bit")
LORA_ADAPTER_DIR = os.environ.get(
    "VIDHANAI_LORA_DIR",
    os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "notebooks",
        "lora_model",
    ),
)

# A real PEFT adapter's safetensors are tens of MB. The repo ships a 133-byte
# placeholder from before Phase 2; anything below this threshold is treated as
# "no adapter" so we never load a stub and present it as a trained model.
MIN_REAL_SAFETENSORS_BYTES = 1_000_000

# When False (default), we never call the local LoRA path even if the adapter
# is on disk. Set VIDHANAI_USE_LORA=1 to enable it after Phase 2 training.
USE_LOCAL_LORA = os.environ.get("VIDHANAI_USE_LORA", "0") == "1"

# ---------------------------------------------------------------------------
# Ollama backend (fine-tuned model on the demo box, served locally on CPU).
#
# The QLoRA adapter from notebooks/lora_model is merged + quantized to a Q4 GGUF
# (see notebooks/export_lora_to_gguf.ipynb) and served by Ollama at
# VIDHANAI_OLLAMA_URL. When VIDHANAI_USE_OLLAMA=1 this backend runs FIRST in the
# generation chain, so the app's summaries come from the locally fine-tuned
# model instead of Groq. Leave it unset on cloud deploys (Render/HF) where the
# model cannot run and groq/compound remains the public-facing backend.
# ---------------------------------------------------------------------------
USE_OLLAMA = os.environ.get("VIDHANAI_USE_OLLAMA", "0") == "1"
OLLAMA_URL = os.environ.get("VIDHANAI_OLLAMA_URL", "http://127.0.0.1:11434/v1")
OLLAMA_MODEL = os.environ.get("VIDHANAI_OLLAMA_MODEL", "vidhanai")
# Cap output length. The 3B on this CPU generates ~8 tokens/s, so a full
# summary (up to ~900 tokens) takes a couple of minutes per bill; summaries are
# DB-cached, so pre-warm the demo bills once. Lower this only if you accept
# cut-off summaries for faster live generation.
def _ollama_max_tokens() -> int:
    try:
        return max(64, int(os.environ.get("VIDHANAI_OLLAMA_MAX_TOKENS", "900")))
    except (TypeError, ValueError):  # pragma: no cover - bad env value
        return 900


OLLAMA_MAX_TOKENS = _ollama_max_tokens()


# ---------------------------------------------------------------------------
# Local LoRA backend (Phase 2)
# ---------------------------------------------------------------------------

_LOCAL_MODEL = None
_LOCAL_TOKENIZER = None
_LOCAL_MODEL_LOADED = False
_LOCAL_MODEL_LOADING = False


def lora_adapter_available() -> bool:
    """Return True iff a *trained* LoRA adapter directory exists on disk.

    Rejects stubs: the repo ships a 133-byte placeholder at notebooks/lora_model
    that must not be treated as a real trained adapter (which is tens of MB).
    """
    if not os.path.isdir(LORA_ADAPTER_DIR):
        return False
    weights = [f for f in os.listdir(LORA_ADAPTER_DIR)
               if f.endswith((".safetensors", ".bin", ".pt"))]
    if not weights:
        return False
    return any(
        os.path.getsize(os.path.join(LORA_ADAPTER_DIR, f)) >= MIN_REAL_SAFETENSORS_BYTES
        for f in weights
    )


def lazy_load_lora_model() -> bool:
    """Load the LoRA adapter + base model into memory once. Phase 2 only."""
    global _LOCAL_MODEL, _LOCAL_TOKENIZER, _LOCAL_MODEL_LOADED, _LOCAL_MODEL_LOADING

    if _LOCAL_MODEL_LOADED or _LOCAL_MODEL_LOADING:
        return _LOCAL_MODEL_LOADED

    if not USE_LOCAL_LORA:
        logger.info("Local LoRA backend disabled (VIDHANAI_USE_LORA != 1).")
        return False

    if not _lazy_load_transformers():
        logger.warning("transformers/peft not installed; local LoRA backend unavailable.")
        return False

    if not lora_adapter_available():
        logger.warning(
            "No trained LoRA adapter found at %s. Run Phase 2 training first.",
            LORA_ADAPTER_DIR,
        )
        return False

    try:
        _LOCAL_MODEL_LOADING = True
        logger.info("Loading local LoRA adapter from %s ...", LORA_ADAPTER_DIR)

        _LOCAL_TOKENIZER = _AutoTokenizer.from_pretrained(LORA_BASE_MODEL)
        device_map = "auto" if _torch.cuda.is_available() else "cpu"
        base_model = _AutoModelForCausalLM.from_pretrained(
            LORA_BASE_MODEL,
            device_map=device_map,
            torch_dtype=_torch.float16 if _torch.cuda.is_available() else _torch.float32,
            low_cpu_mem_usage=True,
        )
        _LOCAL_MODEL = _PeftModel.from_pretrained(base_model, LORA_ADAPTER_DIR)
        _LOCAL_MODEL_LOADED = True
        logger.info("Local LoRA model loaded successfully on %s.", device_map)
    except Exception as exc:  # pragma: no cover - defensive
        logger.exception("Failed to load local LoRA model: %s", exc)
        _LOCAL_MODEL = None
        _LOCAL_TOKENIZER = None
    finally:
        _LOCAL_MODEL_LOADING = False

    return _LOCAL_MODEL_LOADED


def generate_lora_summary(text: str) -> Optional[str]:
    """Run the locally-loaded QLoRA model on ``text``."""
    if not lazy_load_lora_model() or _LOCAL_MODEL is None or _LOCAL_TOKENIZER is None:
        return None

    try:
        messages = [
            {"role": "system", "content": EXPERT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Simplify this legal text:\n\n{text[:6000]}"},
        ]
        prompt = _LOCAL_TOKENIZER.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = _LOCAL_TOKENIZER(prompt, return_tensors="pt")
        if _torch.cuda.is_available():
            inputs = {k: v.to("cuda") for k, v in inputs.items()}

        with _torch.no_grad():
            outputs = _LOCAL_MODEL.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.3,
                top_p=0.9,
                do_sample=True,
                pad_token_id=_LOCAL_TOKENIZER.eos_token_id,
            )

        input_length = inputs["input_ids"].shape[1]
        generated = outputs[0][input_length:]
        return _LOCAL_TOKENIZER.decode(generated, skip_special_tokens=True).strip()
    except Exception as exc:  # pragma: no cover - defensive
        logger.exception("Local LoRA generation failed: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Ollama backend (fine-tuned model, local CPU demo)
# ---------------------------------------------------------------------------

def generate_ollama_summary(text: str) -> Optional[str]:
    """Run the locally-served fine-tuned model through Ollama.

    Talks to Ollama's OpenAI-compatible endpoint (default
    ``http://127.0.0.1:11434/v1``) using the same expert prompt as the Groq and
    LoRA backends, so the model_version stamp tells you honestly which backend
    produced the text. Returns ``None`` on any failure (model not loaded,
    Ollama not running, timeout) so the caller degrades gracefully instead of
    erroring - never fabricates output.
    """
    if not USE_OLLAMA:
        return None
    try:
        import requests as _requests
    except ImportError:  # pragma: no cover - requests is in requirements
        logger.warning("requests not installed; Ollama backend unavailable.")
        return None

    try:
        resp = _requests.post(
            f"{OLLAMA_URL}/chat/completions",
            json={
                "model": OLLAMA_MODEL,
                "messages": [
                    {"role": "system", "content": EXPERT_SYSTEM_PROMPT},
                    {"role": "user", "content": f"Simplify this legal text:\n\n{text[:6000]}"},
                ],
                "temperature": 0.3,
                "top_p": 0.9,
                "max_tokens": OLLAMA_MAX_TOKENS,
            },
            timeout=240,  # CPU 3B can take ~40 s for a full summary; stay generous
        )
        resp.raise_for_status()
        data = resp.json()
        content = (data.get("choices") or [{}])[0].get("message", {}).get("content")
        return (content or "").strip() or None
    except Exception as exc:  # pragma: no cover - network/local server
        logger.warning("Ollama call failed (%s): %s", OLLAMA_URL, exc)
        return None


# ---------------------------------------------------------------------------
# Groq backend (default, production)
# ---------------------------------------------------------------------------

_GROQ_CLIENT = None


def _get_groq_client():
    """Lazy-init the Groq client using GROQ_API_KEY."""
    global _GROQ_CLIENT
    if _GROQ_CLIENT is not None:
        return _GROQ_CLIENT
    if not GROQ_AVAILABLE:
        return None
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        logger.warning("GROQ_API_KEY not set; Groq backend unavailable.")
        return None
    _GROQ_CLIENT = Groq(api_key=api_key)
    return _GROQ_CLIENT


def generate_groq_summary(text: str, model: str = GROQ_MODEL_NAME,
                          retries: int = 1, backoff_s: float = 4.0) -> Optional[str]:
    """Call Groq with the expert prompt. This is the production default.

    ``retries`` is a small number (default 1) of naive retries with fixed
    backoff to ride through transient 429 rate-limit races. On persistent
    failure returns ``None`` and the caller degrades honestly (no fake
    output; the summary is stamped as ``rule_based_extractive_v1``).
    """
    client = _get_groq_client()
    if client is None:
        return None
    import time as _time
    last_exc: Exception | None = None
    for attempt in range(retries + 1):
        try:
            response = client.chat.completions.create(
                messages=[
                    {"role": "system", "content": EXPERT_SYSTEM_PROMPT},
                    {"role": "user", "content": f"Simplify this legal text:\n\n{text[:15000]}"},
                ],
                model=model,
                temperature=0.3,
            )
            return (response.choices[0].message.content or "").strip() or None
        except Exception as exc:  # pragma: no cover - network/api
            last_exc = exc
            if attempt < retries:
                _time.sleep(backoff_s * (attempt + 1))
    logger.exception("Groq API call failed after %d attempts: %s",
                     retries + 1, last_exc)
    return None


# ---------------------------------------------------------------------------
# Guardrails
# ---------------------------------------------------------------------------

_NON_LEGAL_KEYWORDS = (
    "write a story",
    "joke",
    "recipe",
    "poem",
    "how to make a bomb",
    "ignore previous",
    "write code",
    "pretend you are",
)


def check_input_guardrails(query: str) -> tuple[bool, str]:
    """Reject obvious non-legal queries before they reach the model."""
    if not query:
        return True, ""
    lowered = query.lower()
    for kw in _NON_LEGAL_KEYWORDS:
        if kw in lowered:
            return False, (
                "Query rejected: this query appears to be outside the scope of "
                "Indian legislation. Please ask a question related to bills, acts, "
                "or parliamentary proceedings."
            )
    return True, ""


def append_legal_disclaimer(summary: str) -> str:
    """Output guardrail: append the standard legal disclaimer."""
    return summary + LEGAL_DISCLAIMER


# ---------------------------------------------------------------------------
# Sentiment
# ---------------------------------------------------------------------------

def analyze_sentiment(text: str) -> float:
    """Return a polarity score in [-1, 1] for the first 5000 chars of ``text``."""
    if not text:
        return 0.0
    if not TEXTBLOB_AVAILABLE:
        return 0.0
    try:
        return float(TextBlob(text[:5000]).sentiment.polarity)
    except Exception:  # pragma: no cover
        return 0.0


# ---------------------------------------------------------------------------
# Semantic search
# ---------------------------------------------------------------------------

def semantic_search(query: str, n_results: int = 5) -> list[dict]:
    """Query the ChromaDB ``legal_bills`` collection."""
    if not CHROMADB_AVAILABLE:
        logger.warning("chromadb not installed; semantic search disabled.")
        return []

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    db_path = os.path.join(project_root, "instance", "chroma_db")
    if not os.path.isdir(db_path):
        logger.info("ChromaDB not found at %s; skipping semantic search.", db_path)
        return []

    try:
        client = chromadb.PersistentClient(path=db_path)
        ef = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2"
        )
        collection = client.get_collection(name="legal_bills", embedding_function=ef)
        results = collection.query(query_texts=[query], n_results=n_results)
        if not results or not results.get("documents"):
            return []
        documents = results["documents"][0]
        metadatas = (results.get("metadatas") or [[]])[0]
        distances = (results.get("distances") or [[]])[0] if results.get("distances") else []
        return [
            {
                "text": documents[i],
                "metadata": metadatas[i] if i < len(metadatas) else {},
                "distance": distances[i] if i < len(distances) else None,
            }
            for i in range(len(documents))
        ]
    except Exception as exc:  # pragma: no cover
        logger.exception("Semantic search failed: %s", exc)
        return []


# ---------------------------------------------------------------------------
# High-level summarization entry point
# ---------------------------------------------------------------------------

def _format_header(title: str, ministry: str, status: str, introduction_date, date_scraped=None) -> str:
    parts = [f"## {title}", ""]
    if ministry:
        parts.append(f"**Ministry:** {ministry}  ")
    if status:
        parts.append(f"**Status:** {status}  ")
    # Use introduction_date if available, otherwise fall back to date_scraped
    display_date = introduction_date or date_scraped
    if display_date:
        try:
            dt = datetime.fromisoformat(str(display_date).replace("Z", "+00:00"))
            parts.append(f"**Introduced:** {dt.strftime('%B %d, %Y')}  ")
        except Exception:
            pass
    return "\n".join(parts)


def generate_bill_summary(bill_data: dict, content_data: dict) -> dict:
    """Produce a structured summary for one bill.

    Returns a dict with keys: ``summary``, ``summary_type``, ``model_version``,
    ``guardrail_applied``, ``sentiment_score``, ``generated_at``, ``word_count``,
    ``confidence``.
    """
    title = bill_data.get("title", "Untitled Bill")
    ministry = (bill_data.get("ministry") or "").strip()
    status = (bill_data.get("status") or "").strip()
    introduction_date = bill_data.get("introduction_date")
    date_scraped = bill_data.get("date_scraped")

    full_text = (content_data or {}).get("full_text") or ""
    sections = (content_data or {}).get("sections") or []
    paragraphs = (content_data or {}).get("paragraphs") or []

    summary_text = ""
    summary_type = "extractive"
    model_version = "rule_based_extractive_v1"
    confidence = 0.5

    if full_text:
        # Try the configured backends in priority order: locally fine-tuned
        # model (Ollama) → local LoRA → Groq. Enabling the Ollama backend makes
        # the fine-tuned model the generative engine for the running app; when
        # it is unset (cloud deploys) behavior is unchanged and Groq serves.
        backend_chain = []
        if USE_OLLAMA:
            backend_chain.append(("ollama", generate_ollama_summary))
        if USE_LOCAL_LORA:
            backend_chain.append(("local_lora", generate_lora_summary))
        backend_chain.append(("groq_expert", generate_groq_summary))

        for backend_name, backend_fn in backend_chain:
            result = backend_fn(full_text)
            if result:
                header = _format_header(title, ministry, status, introduction_date, date_scraped)
                summary_text = f"{header}\n\n### AI Generative Summary\n{result}"
                summary_type = "generative"
                if backend_name == "ollama":
                    model_version = f"local_ollama_{OLLAMA_MODEL}"
                    confidence = 0.9
                elif backend_name == "local_lora":
                    model_version = f"local_lora_{LORA_BASE_MODEL.split('/')[-1]}"
                    confidence = 0.92
                elif backend_name == "groq_expert":
                    model_version = f"groq_{GROQ_MODEL_NAME}"
                    confidence = 0.88
                break

    # The generative model output already leads with a '## TL;DR' section (see
    # EXPERT_SYSTEM_PROMPT) and contains the full body, so no separate TL;DR
    # extraction/reassembly happens here — earlier code that re-sliced from
    # '## TL;DR' to the next '###' marker swallowed the WHOLE document (models
    # use '##' section headings, so no terminator matched) and then re-appended
    # it, producing a duplicated, confusing summary.

    if not summary_text:
        # Last-resort: rule-based extractive summary.
        summary_text = _extractive_summary(
            title, ministry, status, introduction_date,
            full_text, sections, paragraphs, date_scraped,
        )
        summary_type = "extractive"
        model_version = "rule_based_extractive_v1"
        confidence = 0.6

    summary_with_disclaimer = append_legal_disclaimer(summary_text)
    sentiment_score = analyze_sentiment(full_text)

    return {
        "summary": summary_with_disclaimer,
        "summary_type": summary_type,
        "model_version": model_version,
        "guardrail_applied": True,
        "sentiment_score": sentiment_score,
        "generated_at": datetime.utcnow().isoformat(),
        "word_count": len(summary_with_disclaimer.split()),
        "confidence": confidence,
    }


def generate_quick_summary(bill_data: dict) -> dict:
    """One-line summary used when full text isn't available."""
    title = bill_data.get("title", "Bill")
    ministry = bill_data.get("ministry", "")
    status = bill_data.get("status", "")
    introduction_date = bill_data.get("introduction_date")
    date_scraped = bill_data.get("date_scraped")
    header = _format_header(title, ministry, status, introduction_date, date_scraped)
    sentence = f"This bill titled '{title}'"
    if ministry:
        sentence += f" from the {ministry}"
    if status:
        sentence += f" is currently {status.lower()}"
    else:
        sentence += " is under consideration"
    sentence += ". Detailed provisions and objectives are being analyzed."
    return {
        "summary": append_legal_disclaimer(f"{header}\n\n{sentence}"),
        "summary_type": "quick",
        "model_version": "rule_based_quick_v1",
        "guardrail_applied": True,
        "generated_at": datetime.utcnow().isoformat(),
        "word_count": len(sentence.split()),
        "confidence": 0.5,
    }


def generate_change_narrative(diff: dict) -> dict:
    """Turn a structural diff dict into a human-readable narrative.

    Uses the LLM Service (LoRA + Groq fallback). The diff itself is
    already structured; the LLM only narrates the change list.

    Returns the same dict shape as generate_bill_summary so callers can
    stamp model_version / guardrail_applied uniformly.
    """
    diff_summary = diff.get("diff_summary_text") or ""
    if not diff_summary:
        from services.amendment_service import diff_summary_text
        diff_summary = diff_summary_text(diff)

    # Build a compact prompt with the structural facts the LLM must narrate.
    facts_added = diff.get("facts_added", [])[:10]
    facts_removed = diff.get("facts_removed", [])[:10]
    sections_modified = diff.get("modified_sections", [])[:3]
    sections_added = diff.get("added_sections", [])[:3]
    sections_removed = diff.get("removed_sections", [])[:3]
    stats = diff.get("stats", {})

    # Build explicit, unambiguous facts for the LLM
    added_titles = [s['title'] for s in sections_added]
    removed_titles = [s['title'] for s in sections_removed]
    modified_titles = [s['title'] for s in sections_modified]

    user_payload = (
        f"v1: {diff.get('title_v1','')}\n"
        f"v2: {diff.get('title_v2','')}\n\n"
        f"STRUCTURAL DIFF STATS (MUST BE ACCURATE IN NARRATIVE):\n"
        f"  v1 had {stats.get('v1_sections',0)} section(s); v2 has {stats.get('v2_sections',0)} section(s)\n"
        f"  Sections ADDED in v2 (not in v1): {stats.get('added',0)} — {added_titles if added_titles else 'none'}\n"
        f"  Sections REMOVED in v2 (were in v1): {stats.get('removed',0)} — {removed_titles if removed_titles else 'none'}\n"
        f"  Sections MODIFIED (same title, different content): {stats.get('modified',0)} — {modified_titles if modified_titles else 'none'}\n\n"
        f"FACT CHANGES (penalties, dates, amounts):\n"
        f"  NEW facts in v2 (not in v1): {facts_added if facts_added else 'none'}\n"
        f"  OLD facts REMOVED from v1 (not in v2): {facts_removed if facts_removed else 'none'}\n\n"
        "INSTRUCTIONS:\n"
        "Write a 3-5 sentence plain-English narrative of what changed between v1 and v2.\n"
        "MUST accurately reflect the stats above — do NOT contradict the numbers above.\n"
        "Focus on concrete facts (penalties, dates, jurisdictions) and sections added/removed/modified.\n"
        "Do NOT say 'added X sections' if stats show different numbers.\n"
        "Do NOT include meta-commentary about your approach."
    )

    narrative = ""
    model_version = "rule_based_diff_narrative_v1"
    confidence = 0.55
    if USE_OLLAMA:
        ollama_out = generate_ollama_summary(user_payload)
        if ollama_out:
            narrative = ollama_out
            model_version = f"local_ollama_{OLLAMA_MODEL}"
            confidence = 0.9
    if not narrative and USE_LOCAL_LORA:
        lora_out = generate_lora_summary(user_payload)
        if lora_out:
            narrative = lora_out
            model_version = f"local_lora_{LORA_BASE_MODEL.split('/')[-1]}"
            confidence = 0.9
    if not narrative:
        groq_out = generate_groq_summary(user_payload)
        if groq_out:
            narrative = groq_out
            model_version = f"groq_{GROQ_MODEL_NAME}"
            confidence = 0.85

    if not narrative:
        # Honest rule-based fallback: list the facts verbatim.
        lines = [
            f"Changes between {diff.get('title_v1','v1')} and {diff.get('title_v2','v2')}:",
            diff_summary,
        ]
        narrative = "\n\n".join(lines)

    return {
        "narrative": append_legal_disclaimer(narrative),
        "model_version": model_version,
        "guardrail_applied": True,
        "confidence": confidence,
        "diff_summary_text": diff_summary,
        "facts_added": facts_added,
        "facts_removed": facts_removed,
    }


# ---------------------------------------------------------------------------
# Extractive helpers (last-resort fallback only)
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list[str]:
    if not text:
        return []
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 20]


def _extractive_summary(
    title: str,
    ministry: str,
    status: str,
    introduction_date,
    full_text: str,
    sections: list,
    paragraphs: list,
    date_scraped=None,
) -> str:
    parts = [_format_header(title, ministry, status, introduction_date, date_scraped), ""]

    # Extract TL;DR (3 bullets)
    sentences = _split_sentences(full_text)
    if sentences:
        tldr_bullets = []
        # First sentence = purpose
        tldr_bullets.append(f"• {sentences[0][:200]}")
        # Find penalty/key provision
        for s in sentences[1:6]:
            if any(kw in s.lower() for kw in ['penalty', 'fine', 'imprisonment', 'crore', 'lakh', 'shall', 'must']):
                tldr_bullets.append(f"• {s[:200]}")
                break
        # Last sentence = impact/next step
        if len(sentences) > 2:
            tldr_bullets.append(f"• {sentences[-1][:200]}")

        if len(tldr_bullets) >= 2:
            parts.append("## TL;DR")
            parts.extend(tldr_bullets[:3])
            parts.append("")

    if sentences:
        parts.append("### Overview")
        parts.append(" ".join(sentences[:3]))
    if paragraphs:
        parts.append("\n\n### Key Points")
        for para in paragraphs[:3]:
            if len(para) > 50:
                parts.append(f"- {para}")
    return "\n".join(parts).strip()
