"""
AI Service for Bill Summarization
Uses extractive summarization for quick, accurate summaries
"""
import re
from datetime import datetime
import os
import chromadb
from chromadb.utils import embedding_functions
try:
    from textblob import TextBlob
except ImportError:
    pass # Handled gracefully

# Guardrails
LEGAL_DISCLAIMER = "\n\n---\n**Disclaimer:** This summary was generated by an AI model for educational purposes only. It does not constitute legal advice. Please refer to the official legislative text for accurate legal interpretations."

def check_input_guardrails(query):
    """Input guardrails: ensure query is relevant to legal search."""
    non_legal_keywords = ["write a story", "joke", "recipe", "code", "poem", "how to make", "ignore previous"]
    query_lower = query.lower()
    for kw in non_legal_keywords:
        if kw in query_lower:
            return False, "Query rejected: The semantic distance indicates this query is non-legal. Please ask questions related to Indian legislation."
    return True, ""

def append_legal_disclaimer(summary):
    """Output guardrail: Append legal disclaimer"""
    return summary + LEGAL_DISCLAIMER

def analyze_sentiment(text):
    """Analyze sentiment of the bill text. Returns score between -1.0 and 1.0"""
    if not text:
        return 0.0
    try:
        blob = TextBlob(text[:5000]) # Analyze first 5000 chars for speed
        return blob.sentiment.polarity
    except Exception:
        return 0.0

def semantic_search(query, n_results=5):
    """Query ChromaDB for semantic search."""
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    db_path = os.path.join(project_root, "backend", "instance", "chroma_db")
    
    if not os.path.exists(db_path):
        print(f"ChromaDB not found at {db_path}")
        return []
        
    try:
        client = chromadb.PersistentClient(path=db_path)
        sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
        collection = client.get_collection(name="legal_bills", embedding_function=sentence_transformer_ef)
        
        results = collection.query(
            query_texts=[query],
            n_results=n_results
        )
        
        formatted_results = []
        if results and results['metadatas'] and len(results['metadatas'][0]) > 0:
            for i in range(len(results['documents'][0])):
                formatted_results.append({
                    "text": results['documents'][0][i],
                    "metadata": results['metadatas'][0][i],
                    "distance": results['distances'][0][i] if 'distances' in results and results['distances'] else None
                })
        return formatted_results
    except Exception as e:
        print(f"Error in semantic search: {e}")
        return []


def generate_bill_summary(bill_data, content_data):
    """
    Generate AI summary for a bill
    Uses extractive summarization to create concise summaries
    
    Args:
        bill_data: Bill metadata (title, ministry, status, etc.)
        content_data: Bill content (sections, paragraphs, full_text)
    
    Returns:
        dict with summary and metadata
    """
    
    # Extract key information
    title = bill_data.get('title', 'Untitled Bill')
    ministry = bill_data.get('ministry', '').strip()
    status = bill_data.get('status', '').strip()
    introduction_date = bill_data.get('introduction_date')
    
    # Get content
    full_text = content_data.get('full_text', '')
    sections = content_data.get('sections', [])
    paragraphs = content_data.get('paragraphs', [])
    
    # Build summary
    summary_parts = []
    
    # 1. Title and Basic Info
    summary_parts.append(f"## {title}\n")
    
    # Only add ministry and status if they have values
    if ministry:
        summary_parts.append(f"\n**Ministry:** {ministry}")
    if status:
        summary_parts.append(f"\n**Status:** {status}")
    
    if introduction_date:
        try:
            date_obj = datetime.fromisoformat(introduction_date.replace('Z', '+00:00'))
            formatted_date = date_obj.strftime('%B %d, %Y')
            summary_parts.append(f"\n**Introduced:** {formatted_date}")
        except:
            pass
    
    # 2. Extract bill overview from sections
    overview = extract_bill_overview(sections)
    if overview:
        summary_parts.append(f"\n\n### Overview\n{overview}")
    
    # 3. Extract key objectives from content
    objectives = extract_objectives(full_text, sections)
    if objectives:
        summary_parts.append(f"\n\n### Key Objectives\n{objectives}")
    
    # 4. Extract main provisions
    provisions = extract_provisions(sections)
    if provisions:
        summary_parts.append(f"\n\n### Main Provisions\n{provisions}")
    
    # 5. Extract penalties/enforcement if available
    penalties = extract_penalties(sections, paragraphs)
    if penalties:
        summary_parts.append(f"\n\n### Penalties & Enforcement\n{penalties}")
    
    # 6. Add scope and impact
    scope = extract_scope(full_text, sections)
    if scope:
        summary_parts.append(f"\n\n### Scope\n{scope}")
    
    # 7. Add metadata
    summary_text = ''.join(summary_parts)
    
    # If summary is too short, it means we didn't extract much
    if len(summary_text) < 200:
        summary_text = generate_simple_summary_from_sections(title, sections, paragraphs)
        
    # Append legal disclaimer (Guardrails)
    summary_text = append_legal_disclaimer(summary_text)
    
    # Analyze Sentiment
    sentiment_score = analyze_sentiment(full_text)
    
    return {
        'summary': summary_text,
        'summary_type': 'extractive',
        'generated_at': datetime.utcnow().isoformat(),
        'word_count': len(summary_text.split()),
        'confidence': 0.85,  # Static for now
        'sentiment_score': sentiment_score
    }


def extract_objectives(full_text, sections):
    """Extract key objectives from bill content"""
    objectives = []
    
    # Look for objective-related keywords
    objective_keywords = [
        'objective', 'purpose', 'aim', 'intent', 'seeks to', 
        'is enacted', 'provides for', 'establishes', 'bill seeks'
    ]
    
    # Search in sections
    for section in sections[:10]:  # First 10 sections
        section_title = section.get('section', '').lower()
        section_content = section.get('content', '')
        
        # Check if section content mentions the bill's purpose
        if any(keyword in section_content.lower() for keyword in objective_keywords):
            # Extract relevant sentences
            sentences = extract_sentences(section_content, max_sentences=2)
            for sentence in sentences:
                if len(sentence) > 30 and any(keyword in sentence.lower() for keyword in objective_keywords):
                    objectives.append(f"• {sentence}")
    
    return '\n'.join(objectives[:5]) if objectives else None


def extract_bill_overview(sections):
    """Extract the main overview/introduction of the bill"""
    overview = []
    
    # Usually the first few sections contain the overview
    for section in sections[:5]:
        content = section.get('content', '').strip()
        section_name = section.get('section', '').strip().lower()
        
        # Look for introduction or overview sections
        if not section_name or 'introduc' in section_name.lower() or len(content) > 100:
            # Get meaningful content (skip dates and short texts)
            if len(content) > 50 and not re.match(r'^(Introduced|Passed|Pending)', content):
                sentences = extract_sentences(content, max_sentences=3)
                if sentences:
                    overview.extend(sentences)
                    break
    
    if overview:
        return ' '.join(overview[:3])  # Max 3 sentences
    return None


def generate_simple_summary_from_sections(title, sections, paragraphs):
    """Generate a simple summary when detailed extraction fails"""
    summary_parts = [f"## {title}\n"]
    
    # Get the first substantial section content
    for section in sections:
        content = section.get('content', '').strip()
        if len(content) > 100 and not re.match(r'^(Introduced|Passed|Pending)', content):
            summary_parts.append(f"\n{content}")
            break
    
    # If still not enough, use paragraphs
    if len(''.join(summary_parts)) < 200 and paragraphs:
        summary_parts.append(f"\n\n### Key Points\n")
        for para in paragraphs[:3]:
            if len(para) > 50:
                summary_parts.append(f"• {para}\n")
    
    return ''.join(summary_parts)


def extract_penalties(sections, paragraphs):
    """Extract penalty and enforcement information"""
    penalties = []
    
    # Look for penalty-related sections
    penalty_keywords = ['penalty', 'penalties', 'offence', 'punishment', 'fine', 'imprisonment']
    
    for section in sections:
        section_name = section.get('section', '').lower()
        content = section.get('content', '')
        
        if any(keyword in section_name for keyword in penalty_keywords):
            sentences = extract_sentences(content, max_sentences=3)
            for sentence in sentences:
                if len(sentence) > 20:
                    penalties.append(f"• {sentence}")
    
    # Also check paragraphs
    if not penalties:
        for para in paragraphs:
            if any(keyword in para.lower() for keyword in penalty_keywords):
                if len(para) > 50:
                    penalties.append(f"• {para}")
                    if len(penalties) >= 2:
                        break
    
    return '\n'.join(penalties[:3]) if penalties else None


def extract_provisions(sections):
    """Extract main provisions from sections"""
    provisions = []
    
    # Look for provision-related sections
    provision_keywords = [
        'provision', 'regulation', 'prohibition', 'promotion',
        'authority', 'power', 'requirement', 'establishment'
    ]
    
    for section in sections:
        section_name = section.get('section', '').strip()
        content = section.get('content', '')
        
        # If section has a meaningful name, use it
        if section_name and len(section_name) > 5:
            # Check if it's a provision section
            if any(keyword in section_name.lower() for keyword in provision_keywords):
                # Extract first sentence or two
                sentences = extract_sentences(content, max_sentences=2)
                if sentences:
                    provision_text = ' '.join(sentences)
                    provisions.append(f"**{section_name}:** {provision_text}")
    
    return '\n\n'.join(provisions[:5]) if provisions else None


def extract_scope(full_text, sections):
    """Extract scope and applicability"""
    scope_text = []
    
    # Look for scope-related keywords
    scope_keywords = [
        'applies to', 'applicable', 'scope', 'extends to',
        'shall apply', 'jurisdiction', 'territory'
    ]
    
    # Search in full text
    if full_text:
        for keyword in scope_keywords:
            pattern = rf'[^.]*{keyword}[^.]*\.'
            matches = re.findall(pattern, full_text, re.IGNORECASE)
            for match in matches[:2]:
                cleaned = match.strip()
                if 20 < len(cleaned) < 200:
                    scope_text.append(f"• {cleaned}")
    
    return '\n'.join(scope_text[:3]) if scope_text else None


def extract_sentences(text, max_sentences=3):
    """Extract sentences from text"""
    if not text:
        return []
    
    # Split by period, but be careful with abbreviations
    sentences = re.split(r'\.(?!\d)(?![A-Z]{1,3}\.)', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    # Clean up
    clean_sentences = []
    for sentence in sentences[:max_sentences]:
        # Remove extra whitespace
        sentence = ' '.join(sentence.split())
        # Remove leading numbers/bullets
        sentence = re.sub(r'^[\d\.\-\•\*\(\)]+\s*', '', sentence)
        if sentence:
            clean_sentences.append(sentence)
    
    return clean_sentences


def generate_quick_summary(bill_data):
    """
    Generate a quick one-line summary when full content is not available
    """
    title = bill_data.get('title', 'Bill')
    ministry = bill_data.get('ministry', '')
    status = bill_data.get('status', '')
    
    summary = f"This bill titled '{title}' "
    
    if ministry:
        summary += f"from the {ministry} "
    
    if status:
        summary += f"is currently {status.lower()}. "
    else:
        summary += "is under consideration. "
    
    summary += "Detailed provisions and objectives are being analyzed."
    
    return {
        'summary': summary,
        'summary_type': 'quick',
        'generated_at': datetime.utcnow().isoformat(),
        'word_count': len(summary.split()),
        'confidence': 0.5
    }
