"""
VidhanAI LoRA round-trip helper (Kaggle <-> local).

Two directions:

1. DATASET OUT (local -> Kaggle): package the train/val/test JSONL so it can be
   dragged into a new Kaggle Dataset (Data tab -> "New Dataset" -> upload this zip).

       python roundtrip_lora.py --bundle-dataset

   Produces:  datasets/vidhanai_ft_dataset.zip

2. ADAPTER IN (Kaggle -> local): unzip the lora_model/ folder you downloaded
   from the Kaggle notebook session into notebooks/lora_model/ with sanity
   checks (must contain adapter_config.json and a real safetensors file).

       python roundtrip_lora.py --extract-adapter path/to/lora_model.zip

   After extraction, set VIDHANAI_USE_LORA=1 and run:
       cd backend/scripts/ml_pipeline && python 3_calculate_metrics.py

This is a thin helper on top of zipfile+argparse (no extra deps). For official
Kaggle CLI upload (instead of drag-and-drop) use the `kaggle` CLI; this script
just prepares a clean archive.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

DATASET_DIR = REPO_ROOT / "backend" / "scripts" / "ml_pipeline" / "datasets"
LORA_MODEL_DIR = SCRIPT_DIR / "lora_model"
BUNDLE_OUT = SCRIPT_DIR / "vidhanai_ft_dataset.zip"

EXPECTED_DATASET_FILES = ("train.jsonl", "val.jsonl", "test.jsonl")
MIN_REAL_SAFETENSORS_BYTES = 1_000_000  # a stub placeholder is ~133 bytes


def bundle_dataset() -> Path:
    """Zip datasets/*.jsonl into a single archive for a Kaggle Dataset upload."""
    missing = [f for f in EXPECTED_DATASET_FILES if not (DATASET_DIR / f).exists()]
    if missing:
        print(f"WARNING: missing dataset files: {missing}")
        print("Do you need to run 'python 1_generate_dataset.py' first?")
    else:
        for f in EXPECTED_DATASET_FILES:
            n = sum(1 for _ in (DATASET_DIR / f).open(encoding="utf-8"))
            print(f"  {f}: {n} rows")

    if BUNDLE_OUT.exists():
        BUNDLE_OUT.unlink()

    with zipfile.ZipFile(BUNDLE_OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in EXPECTED_DATASET_FILES:
            p = DATASET_DIR / f
            if p.exists():
                zf.write(p, arcname=f)
        # Include an auto-generated dataset-metadata.json so `kaggle datasets
        # create -p` works out of the box.
        metadata = {
            "id": "vidhanaiteam/vidhanai-ft-dataset",
            "title": "VidhanAI Fine-Tuning Dataset",
            "subtitle": "Indian legislative bills with expert-style simplified summaries (Groq distilled).",
            "description": "Instruction-format JSONL for QLoRA fine-tuning of Llama-3.2-3B on Indian bill simplification. Generated by backend/scripts/ml_pipeline/1_generate_dataset.py.",
            "licenses": [{"name": "CC0-1.0"}],
        }
        zf.writestr("dataset-metadata.json", json.dumps(metadata, indent=2))

    size_kb = BUNDLE_OUT.stat().st_size / 1024
    print(f"\nWrote {BUNDLE_OUT.name} ({size_kb:.0f} KB)")
    print("Next: kaggle.com -> Datasets -> New Dataset -> upload this zip, or use:")
    print("  kaggle datasets create -p " + str(REPO_ROOT / "notebooks"))
    return BUNDLE_OUT


def _safetensors_are_real(adapter_dir: Path) -> tuple[bool, str]:
    """Check the adapter weights look trained, not stubbed."""
    safetensors = list(adapter_dir.glob("*.safetensors"))
    if not safetensors:
        return False, "no .safetensors file found"
    sizes = {st.name: st.stat().st_size for st in safetensors}
    for name, size in sizes.items():
        if size < MIN_REAL_SAFETENSORS_BYTES:
            return False, f"{name} is only {size} bytes — looks like a stub, not a trained adapter"
    return True, f"weights OK: {sizes}"


def extract_adapter(zip_path: str) -> Path | None:
    """Unzip a downloaded lora_model/ into notebooks/lora_model/."""
    src = Path(zip_path)
    if not src.exists():
        print(f"ERROR: {src} not found.")
        return None

    tmp = Path(tempfile.mkdtemp(prefix="lora_extract_"))
    try:
        with zipfile.ZipFile(src) as zf:
            zf.extractall(tmp)

        # The zip may wrap the folder (lora_model/...) or contain files at root.
        candidate = tmp / "lora_model" if (tmp / "lora_model").is_dir() else tmp
        if not (candidate / "adapter_config.json").exists():
            print("ERROR: extracted archive has no adapter_config.json at the top level.")
            print("Extracted files:", [p.name for p in tmp.rglob("*")][:25])
            return None

        ok, msg = _safetensors_are_real(candidate)
        if not ok:
            print(f"ERROR: {msg}")
            print("This looks like the 133-byte stub, not a trained adapter. Aborting.")
            return None

        # Move over, atomically-ish: rename old, copy new, delete backup.
        backup = None
        if LORA_MODEL_DIR.exists():
            backup = LORA_MODEL_DIR.with_name("lora_model_backup_pre_phase2")
            if backup.exists():
                shutil.rmtree(backup)
            LORA_MODEL_DIR.rename(backup)
        shutil.copytree(candidate, LORA_MODEL_DIR)
        if backup:
            shutil.rmtree(backup)

        print(f"SUCCESS: real adapter installed at {LORA_MODEL_DIR}")
        print(f"  {ok and msg}")
        print("\nNext steps:")
        print("  1. export VIDHANAI_USE_LORA=1")
        print("  2. cd backend/scripts/ml_pipeline && python 3_calculate_metrics.py")
        print("  3. python ../../scripts/... to regenerate docs/metrics_summary.json + bootstrap CIs")
        return LORA_MODEL_DIR
    except Exception as exc:  # pragma: no cover
        print(f"ERROR extracting: {exc}")
        return None
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle-dataset", action="store_true",
                        help="Zip datasets/*.jsonl for Kaggle Dataset upload.")
    parser.add_argument("--extract-adapter", metavar="ZIP",
                        help="Path to the lora_model.zip downloaded from Kaggle.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.bundle_dataset and not args.extract_adapter:
        print(__doc__)
        return 1
    if args.bundle_dataset:
        bundle_dataset()
    if args.extract_adapter:
        extract_adapter(args.extract_adapter)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())