import { useState } from 'react';
import './Subscribe.css';

export default function Subscribe() {
  const [formData, setFormData] = useState({
    email: '',
    keywords: '',
    ministries: '',
    email_frequency: 'instant'
  });
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState({ type: '', text: '' });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage({ type: '', text: '' });

    try {
      // Parse comma-separated keywords and ministries
      const keywordsArray = formData.keywords
        .split(',')
        .map(k => k.trim())
        .filter(k => k.length > 0);
      
      const ministriesArray = formData.ministries
        .split(',')
        .map(m => m.trim())
        .filter(m => m.length > 0);

      const response = await fetch('http://localhost:5000/api/subscribe', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email: formData.email,
          keywords: keywordsArray,
          ministries: ministriesArray,
          email_frequency: formData.email_frequency
        }),
      });

      const data = await response.json();

      if (response.ok) {
        // Trigger n8n confirmation workflow
        try {
          await fetch('http://localhost:5678/webhook/subscription-confirmation', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              email: data.subscription.email,
              keywords: data.subscription.keywords,
              ministries: data.subscription.ministries,
              email_frequency: data.subscription.email_frequency,
              subscription_id: data.subscription.id
            })
          });
        } catch (webhookError) {
          console.error('Webhook error:', webhookError);
          // Don't fail the subscription if webhook fails
        }

        setMessage({
          type: 'success',
          text: '✅ ' + data.message + ' Check your email for confirmation!'
        });
        // Reset form
        setFormData({
          email: '',
          keywords: '',
          ministries: '',
          email_frequency: 'instant'
        });
      } else {
        setMessage({
          type: 'error',
          text: '❌ ' + (data.error || 'Failed to subscribe. Please try again.')
        });
      }
    } catch (error) {
      console.error('Subscription error:', error);
      setMessage({
        type: 'error',
        text: '❌ Network error. Please check your connection and try again.'
      });
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  return (
    <div className="subscribe-page">
      <div className="subscribe-container">
        <div className="subscribe-header">
          <h1>📧 Subscribe to Bill Alerts</h1>
          <p className="subtitle">
            Get instant email notifications when new bills matching your interests are published
          </p>
        </div>

        <div className="info-cards">
          <div className="info-card">
            <div className="info-icon">🔔</div>
            <h3>Instant Alerts</h3>
            <p>Be the first to know when relevant bills are introduced</p>
          </div>
          <div className="info-card">
            <div className="info-icon">🤖</div>
            <h3>AI Summaries</h3>
            <p>Receive easy-to-read summaries generated by AI</p>
          </div>
          <div className="info-card">
            <div className="info-icon">🎯</div>
            <h3>Custom Keywords</h3>
            <p>Filter bills by your specific topics of interest</p>
          </div>
        </div>

        <form className="subscribe-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="email">
              <span className="label-icon">📧</span>
              Email Address *
            </label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="your.email@example.com"
              required
              className="form-input"
            />
            <span className="input-hint">We'll send alerts to this email</span>
          </div>

          <div className="form-group">
            <label htmlFor="keywords">
              <span className="label-icon">🔑</span>
              Keywords (comma-separated)
            </label>
            <input
              type="text"
              id="keywords"
              name="keywords"
              value={formData.keywords}
              onChange={handleChange}
              placeholder="e.g., gaming, tax, environment, healthcare"
              className="form-input"
            />
            <span className="input-hint">
              Enter topics you want to track (e.g., "gaming, finance, education")
            </span>
          </div>

          <div className="form-group">
            <label htmlFor="ministries">
              <span className="label-icon">🏛️</span>
              Ministries (comma-separated, optional)
            </label>
            <input
              type="text"
              id="ministries"
              name="ministries"
              value={formData.ministries}
              onChange={handleChange}
              placeholder="e.g., Ministry of Finance, Ministry of Health"
              className="form-input"
            />
            <span className="input-hint">
              Filter by specific government ministries
            </span>
          </div>

          <div className="form-group">
            <label htmlFor="email_frequency">
              <span className="label-icon">⏰</span>
              Email Frequency
            </label>
            <select
              id="email_frequency"
              name="email_frequency"
              value={formData.email_frequency}
              onChange={handleChange}
              className="form-select"
            >
              <option value="instant">Instant - As soon as bills are published</option>
              <option value="daily">Daily Digest - Once per day</option>
              <option value="weekly">Weekly Summary - Once per week</option>
            </select>
            <span className="input-hint">Choose how often you want to receive emails</span>
          </div>

          {message.text && (
            <div className={`message ${message.type}`}>
              {message.text}
            </div>
          )}

          <button type="submit" className="submit-btn" disabled={loading}>
            {loading ? (
              <>
                <span className="spinner-small"></span>
                Subscribing...
              </>
            ) : (
              <>
                <span>🔔</span>
                Subscribe to Alerts
              </>
            )}
          </button>
        </form>

        <div className="subscribe-footer">
          <p className="privacy-note">
            🔒 Your email is safe with us. We only send notifications about matching bills.
            You can unsubscribe anytime.
          </p>
        </div>
      </div>
    </div>
  );
}
